project:
  type: book
  output-dir: _book
  resources:
    - images/
    - banner.html
    - scripts/
    - fonts/

# --- to publish the website on github ---

execute:
  freeze: auto # only re-renders .qmd files when they have been modified
  echo: true
  warning: false

jupyter: python3

# ----------------------------------------

book:
  title: "Hydrophone Handbook"
  date: today
  date-format: "MMMM D, YYYY"

  
  chapters:
    - index.qmd
    - sections/2-whats-new.qmd
    - sections/3-hydrophone-life-cycle.qmd
    - sections/4-how-do-hydrophones-work.qmd
    - sections/5-sound-in-the-ocean.qmd
    - sections/6-ocean-soundscape-and-taxonomy.qmd
    - sections/7-examples-of-sounds.qmd
    - sections/8-onc-hydrophone-network.qmd
    - sections/9-hydrophone-array-design.qmd
    - sections/10-calibration-hydrocal.qmd
    - sections/11-data-products.qmd
    - sections/12-data-access.qmd
    - sections/13-data-diversion.qmd
    - sections/14-science-and-applications-at-onc.qmd
    - sections/15-useful-equations.qmd
    - sections/16-hydrophone-models.qmd
    - sections/17-glossary.qmd

  sidebar:
    style: "docked"
    background: "#003366"
    foreground: "#ffffff"
    collapse-level: 2


format:
  html:
    theme: quartz
    smooth-scroll: true
    include-in-header: banner.html
    css: styles.css
    navigation:
      full-logo: true
      inter-item-area: true
    toc: true
    number-sections: false
    sidebar-toc: true
    toc-depth: 2
    sticky-sidebar: true
    page-layout: article
    self-contained: false