project:
  type: book
  output-dir: _book
  resources:
    - images/
    - banner.html

book:
  title: "Hydrophone Handbook"

  
  chapters:
    - index.qmd
    - sections/life-cycle.qmd
    - sections/how-hydrophones-work.qmd 
    - sections/sound-propagation.qmd
    - sections/ocean-soundscape-taxonomy.qmd
    - sections/sound-examples.qmd
    - sections/hydrophone-network.qmd
    - sections/array-design.qmd
    - sections/calibration.qmd
    - sections/data-products.qmd
    - sections/data-access.qmd
    - sections/data-diversion.qmd
    - sections/monitoring-troubleshooting.qmd
    - sections/science.qmd
    - sections/useful-equations.qmd
    - sections/hydrophone-specs.qmd
    - sections/list-of-onc-publications.qmd
    - sections/glossary.qmd
    

  sidebar:
    style: "docked"
    background: "#003366"
    foreground: "#ffffff"
    collapse-level: 2


format:
  html:
    theme: quartz
    smooth-scroll: true
    include-in-header: banner.html
    css: styles.css
    navigation:
      full-logo: true
      inter-item-area: true
    toc: true
    number-sections: false
    sidebar-toc: true
    toc-depth: 2
    sticky-sidebar: true
    page-layout: article
    self-contained: true
  pdf:
    pdf-engine: xelatex
    toc: true
    toc-depth: 3
    number-sections: true
    classoption: [11pt]
    include-in-header:
      text: |
        \usepackage{enumitem}
        
        \renewlist{itemize}{itemize}{20}
        \setlist[itemize]{label=\textbullet}
        \let\oldtoc\tableofcontents
        \renewcommand{\tableofcontents}{\oldtoc\newpage} # Forces content to start on a fresh page
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - bottom=20mm