---
title: Hydrophone Life Cycle
---

This section outlines the end-to-end journey of a hydrophone at ONC, from the initial purchase and contract to long-term data analysis.
Thie life cycle is based on Aghaei et al., 2024: **Best Practices for Managing Passive Acoustics Data at Ocean Networks Canada**.

Hydrophones have been in use at ONC since 2006, totalling more than 700 TB of archived data.

The life cycle workflow ensures that data is not just collected, but are **FAIR** (Findable, Accessible, Interoperable, and Reusable).
ONC commits to share and preserve data long-term. 


[INSERT DIAGRAM OF LIFE CYCLE/DATA FLOW]


# 1. Planning and Governance

*Teams involved: Science, DAQ, DSO, Engineers*

Before a hydrophone is deployed in the water, the following legal and technical steps must be taken: 

* **Data Agreements**: ONC establishes legal agreements to define data ownership, usage restrictions, and attribution.
* **Stewardship**: Data Stewards (DSO) apply standardized metadata and attributions to ensure the sensor is *discoverable*.
* **Product Definition**: We identify new data products the community might need.


# 2. Data Collection & Signal Chain

*Teams involved: DAQ, DSO, Systems, Marine Ops, Engineers*

* **Hardware**: We primarily use **Ocean Sonics** (HF/AF) and **GeoSpectrum** (from JASCO distributor) instruments, deployed as single units or four-element arrays.
* **Calibration (HydroCal)**: Instruments undergo rigorous pre-deployment and post-recovery calibration to ensure accuracy. If sensors drift, they are returned to the manufacturer.
* **Data Diversion**: Hydrophones are "Tier 1" instruments, meaning that the data streams are subject to diversion by the Royal Canadian Navy and US Navy before reaching the ONC archive.
* **Data Transmission**:
	* Acoustic Data: Transferred as raw audio (.wav or .flac).
	* Ancillary Data: Instrument "health" (temperature, humidity, clock drift) is transmitted without diversion to minitor device's status (only for Ocean Sonics). Also referred to as auxiliary data. 
* **Data Processing**: Performed to generate Spectral Data (HSD) in MAT format, and Spectral Density Plots (HSDP) the raw audio files, and archived.
* **Data Availability**: Data is made readily available (within a few minutes) to end-users through Oceans 3.0.

# 3. Commissioning

*Teams involved: DAQ, DSO*

Once a hydrophone is deployed and recording data, the commissioning of the device starts.
This process is designed to catch technical issues early and ensures the data is "science-ready".

* **Immediate Post-Deployment**: Immediately after deployment, we confirm the instrument is able to record and send data to ONC archive. A public annotation is created in Oceans 3.0 to mark the start of the data streaming. A JIRA ticket is created which consolidates all relevant information.
* **1-2 Months Post-Deployment**: A detailed analysis of data stream is performed, and several elements are analyzed including the presence of noise, saturation, array consistency (for 4 elements arrays), auxiliary data.

The commissioning ticket is closed one the data is confirmed found in the Hydrophone Data Viewer, accessible through ONC API, and that the data products are generated correctly.

For the complete procedure: [Hydrophone Commissioning Procedure](https://internal.oceannetworks.ca/spaces/ONCData/pages/272761113/Hydrophone+commissioning+procedure)


# 4. Data Quality & Assurance

*Teams involved: DAQ, Science, Systems*

Because hydrophone data is classified as *complex* data (unlike *scalar* data), standard automated QAQC (like those for temperature or salinity) does not yet exist.

* **Manual Inspection**: The DAQ team performs daily visual checks for issues like clipping, electronic interference, energy spikes, sensitivity drifts.
* **Annotations**: Any unusual events or data gaps (caused by network maintenance, instrument failure, communication down) are recorded as annotations in Oceans 3.0 so researchers know why data might be missing.


# 5. Metadata & Standards

*Teams involved: DSO*

To make our data globally compatible, we follow strict international standards:

* **ISO 19115**: Governs our high-level metadata records
* **Global Catalogues**: We align with IOOS, SeaDataNet and SeaVox device categories.
* **FAIR Principles**: Ensuring every byte of data is Findable, Accessible, Interoperable, and Reusable.
* **Device Action**: Every event in a hydrophone life cycle, from deplyoment, calibrations, to recovery, is recorded as a permanent action in the database.

# 6. Preservation & Storage

*Teams involved: Software, DSO, Systems*

* **Primary Storage**: Terabytes of data are stored locally at the University of Victoria data center.
* **Redundancy**: A complete offsite backup is maintained to prevent data loss, and also shares data processing load.


# 7. Access & Analysis
* Teams involved: Science, DSO, End-Users*

* **Discovery**: Users find data via Oceans 3.0 using Data Search, the Hydrophone Viewer (5-minute spectrogram previews), or the API.
* **Identification**: Each dataset is assigned a **DOI** (Digital Object Identifier) to ensure researchers can cite the specific data they used in their papers.


# 9. Recovery & Decommissioning

*Teams involved: DSO, MarineOps, Systems*

The end of a deployement does not mean the end of a instrument's use.
Hydrophones are often re-deployed during the ONC maintenance cruises, or returning to MTC of the manufacturer for maintenance.

* **Post-Recovery Calibration**: Once a hydrophone is pulled out of the water, calibration is performed to check if sensitivity shifted dramatically while underwater. If the before and after are very different, the instrument is often sent back to the manufacturer.
* **Re-Deployment**: Hydrophones are often re-deployed at the same location, or at a new site. If moved to a different site, the instrument keeps its device code, but the device id will be re-assigned.
* **Permanent Decommissioning (Goodbye)**: When an instrument reaches the end of its functional life or can no longer be repaired, it is officially *decommissioned* in the database.
