---
title: Monitoring & Troubleshooting
---

Procedure for addressing common failures (e.g. files not streaming: make INSTR ticket and tag Systems (@nvops) to request power cycle)

create a timeline: validation -> commissioning -> occasional checks -> decommisioning


# Validation

data validation:
- anything before the deployment, while the device is still at MTC
- tank test
- extra ocean sonics validation test (piston)

# Commissioning
confluence page: https://internal.oceannetworks.ca/pages/resumedraft.action?draftId=272761007&draftShareId=20e85281-232e-4b9e-b2ac-fbe56256798a&
data commissioning:

- once deployed, as it starts streaming the data
- create a commisioning JIRA DATA ticket (see example for hydrophone)
	- put general info (device name, device ID, device Code, current deployment, device history, calibration date)
- create a commisioning annotation, then close once commisioning is done
	- check if there are other open annotations to this device
	- check sampling rate
	- no need for primary sensor for hydrophones
- check data stream in oceans 3.0
	- over a few months of data
	- if possible, compare incoming spectrogram to past devices at same location (compare sensitivities/noise levels)
- device action in oceans 3.0
- close commisioning annotation
- assign a reviewer in JIRA (the other DAQ IPP), they will review and close the ticket. reivew takes ~30 min. (there is a confluence page)
	

https://internal.oceannetworks.ca/spaces/ONCData/pages/9344555/Data+Commissioning


# List of common issues and potential root causes:

* No audio data stream -> Junction Box down, network down
* Audio data archived but no .mat/.png -> check with DSO, this might be related to sensitivity curve not updated. This is an internal software system-related problem.
* Very bad data -> instrument health (temp, humidity, battery), biofouling (very hard to detect, happens over the course of several months), interference that's masking data significantly (from nearby instruments)
* clock synchronization (onc Links & icLinks)

# How to report an instrument issue

* is it related to the instrument itself/data quality? INSTR ticket
* is it related to data stream? DSO or DMAS ticket (make sure missing data for the instrument only, otherwise it could be the network down in that case this is not isolated)
* is it related to 


# Using data to assess system problems
* wav/flac: 
* spectrogram: useful for detecting clipping, interference, instrument failure (totally black)
* spd plots: useful for detecting ambient noise, anomalies, power supply interference (electrical noise, mechanical noise)



# Case Studies
